trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true

- script: |
    python -m venv env
    source env/bin/activate
    pip install -r requirements.txt
    pytest --cov=.
  displayName: 'Run unit tests with coverage'

- script: |
    coverage xml
    python-codacy-coverage -r coverage.xml
  displayName: 'Publish coverage results'
